# global:
#   existingSecret: openldap-secret

# persistence:
#   enabled: true
#   size: 1Gi
phpldapadmin: 
  ingress:
    ingressClassName: nginx
    hosts:
    - phpldapadmin.k3s.demo

replicaCount: 1

ltb-passwd:
  enabled: false

env: 
  LDAP_ROOT: dc=idfc,dc=com

service:
  type: LoadBalancer

# Default password: Not@SecurePassw0rd