apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret # Replace with the name of your secret
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ=
  mysql-replication-password: cGFzc3dvcmQ=
  mysql-password: TXlzcWxzZWNyZXQxMjNA
